<?php
$blogId = $block->getBlogId();
$blogComments = $block->getBlogComment();

$saveCommentUrl = $block->getUrl('*/comment/save');
$loginUrl = $block->getUrl('customer/account/login/referer/aHR0cDovL21hZ2VudG8yLnRlc3Q6ODEvYmxvZy9zaG93L2luZGV4L2lkLzEv/');

$isLogged = $block->checkIsLogin();
?>
<?php if ($blogId < 0 || count($blogComments->getData()) == 0) : ?>
    <h2>No such Blog</h2>
<?php else : ?>
    <h3>Comments</h3>
    <form id="commentForm">
        <?php echo $this->getBlockHtml('formkey') ?>
        <!-- <area type="text" name="content" id="content" placeholder="Enter your comment" required> -->
        <textarea name="content" id="content" cols="30" rows="10" placeholder="Enter your comment" required></textarea>
        <input type="hidden" name="customer_id" id="customer_id" value="2">

        <input type="hidden" name="blog_id" id="blog_id" value="<?= $blogId ?>">
        <br>
        <button class="btn btn-submit" type="submit" id='btnSubmit'>Submit</button>
    </form>
<?php endif; ?>

<div class="container padding-30" id="comments">

    <?php foreach ($blogComments as $comment) : ?>
        <div class="comment">
            <b><?= $comment->getFirstname() . ' ' . $comment->getMiddlename() . ' ' . $comment->getLastname() ?></b>
            <span><?= $comment->getEmail() ?></span>
            <br>
            <span><?= date("d/m/Y H:i", strtotime($comment->getCreatedAt())) ?></span>
            <p><?= $comment->getContent() ?></p>
            <br>
        </div>
        <?php ?>
    <?php endforeach; ?>
</div>

<script type="text/javascript">
    require([
        "jquery",
        "mage/mage"
    ], function($) {
        $(document).ready(function() {

            $('#commentForm').mage(
                'validation', {
                    submitHandler: function(form) {
                        var saveCommentUrl = "<?php echo $saveCommentUrl ?>";
                        var isLogged = "<?= $isLogged ?>";
                        // console.log(isLogged);
                        if (isLogged == 'false') {
                            window.location.href = "<?= $loginUrl ?>";
                        } else {
                            var data = $('#commentForm').serialize();
                            $.ajax({
                                url: saveCommentUrl,
                                data: data,
                                type: 'POST',
                                dataType: 'json',
                                showLoader: true,
                                // cache: false,
                                success: function(data, status, xhr) {
                                    $('#comments').empty();

                                    for (var key in data) {

                                        let middlename = data[key].middlename ? data[key].middlename : "";
                                        let createdAt = new Date(data[key].created_at);
                                        let createdAtFormat = createdAt.getDate() + '/' + (createdAt.getMonth() + 1) + '/' + createdAt.getFullYear() +
                                            " " + createdAt.getHours() + ':' + createdAt.getMinutes();

                                        console.log(middlename);
                                        $('#comments').append(
                                            "<div class='comment'> <b>" + data[key].firstname + ' ' + middlename + ' ' + data[key].lastname + " </b>" +
                                            "<span>" + data[key].email + "</span>" +
                                            "<br>" +
                                            "<span>" + createdAtFormat + "</span>" +
                                            "<p>" + data[key].content + "</p>" +
                                            "<br>" +
                                            "</div>"

                                        );

                                    }

                                    $("#commentForm").trigger('reset');
                                },
                                error: function(xhr, status, errorThrown) {

                                }
                            });
                        }

                    }

                }
            );
        });
    });
</script>
