<h2>Blog</h2>
<?php

$blogs = $block->getBlogPaginate();
$baseUrl = $block->getBaseUrl();
$totalPage = $block->getTotalPage();
$currentPage = $block->getCurrentPage();

// var_dump($blogs->getData());
// die();
?>
<?php foreach ($blogs as $blog) : ?>
    <div>
        <a href="<?= $baseUrl . 'blog/show/index/' . 'id/' . $blog->getBlogEntityId() ?>">
            <span>
                <?= $blog->getTitle(); ?>
            </span>
        </a>
    </div>
<?php endforeach; ?>

<a href="<?= $baseUrl . 'blog/all/index/' . 'page/' . '1' ?>">First</a>

<?php for ($i = $currentPage - 2; $i <= $currentPage + 2; $i++) : ?>

    <?php if ($i < 2) : ?>
        <?php continue; ?>
    <?php endif; ?>
    <?php if ($i == $currentPage) : ?>
        <a><?= $i ?></a>

        <?php continue; ?>
    <?php endif; ?>
    <a href="<?= $baseUrl . 'blog/all/index/' . 'page/' . $i ?>"><?= $i ?></a>

<?php endfor; ?>
<a href="<?= $baseUrl . 'blog/all/index/' . 'page/' . $totalPage ?>">Last</a>
