<?php
$blogs = $block->getBlogPaginate();
$baseUrl = $block->getBaseUrl();
$totalPage = $block->getTotalPage();
$currentPage = $block->getCurrentPage();
?>

<div class="container">
    <?php foreach ($blogs as $blog) : ?>
        <div class="item mb-5">
            <div class="media">
                <a class="more-link" href="<?= $baseUrl . 'blog/show/index/' . 'id/' . $blog->getBlogEntityId() ?>">
                    <img class="mr-3 img-fluid post-thumb d-md-flex" src="http://magento2.test:81/media/wysiwyg/blog/jean.jpg" alt="ok" width="100" height="100">
                </a>
                <div class="media-body">
                    <h3 class="title mb-1"><a href="<?= $baseUrl . 'blog/show/index/' . 'id/' . $blog->getBlogEntityId() ?>"> <?= $blog->getTitle(); ?></a></h3>
                    <!-- <div class="meta mb-1"><span class="date">Published 3 months ago</span><span class="time">5 min read</span><span class="comment"><a href="#">4 comments</a></span></div> -->

                </div>
            </div>
        </div>
    <?php endforeach; ?>



    <?php if ($currentPage > 1 && $currentPage < $totalPage) : ?>
        <nav class="blog-nav nav nav-justified my-5">
            <a class="nav-link-prev nav-item nav-link rounded-left" href="<?= $baseUrl . 'blog/all/index/' . 'page/' . ($currentPage - 1) ?>">Previous<i class="arrow-prev fas fa-long-arrow-alt-left"></i></a>
            <a class="nav-link-next nav-item nav-link rounded-right" href="<?= $baseUrl . 'blog/all/index/' . 'page/' . ($currentPage + 1) ?>">Next<i class="arrow-next fas fa-long-arrow-alt-right"></i></a>
        </nav>
    <?php elseif ($currentPage == 1) : ?>
        <nav class="blog-nav nav nav-justified my-5">
            <a class="nav-link-next nav-item nav-link rounded-right" href="<?= $baseUrl . 'blog/all/index/' . 'page/' . ($currentPage + 1) ?>">Next<i class="arrow-next fas fa-long-arrow-alt-right"></i></a>
        </nav>
    <?php else : ?>
        <nav class="blog-nav nav nav-justified my-5">
            <a class="nav-link-prev nav-item nav-link rounded-left" href="<?= $baseUrl . 'blog/all/index/' . 'page/' . ($currentPage - 1) ?>">Previous<i class="arrow-prev fas fa-long-arrow-alt-left"></i></a>
        </nav>
    <?php endif; ?>

</div>
