<h3>Private content</h3>

<div class="practice-custom-section" data-bind="scope: 'custom_section_data'">

    <div data-bind="foreach: customsection().data">
        <a data-bind="attr: { href:  url }">
            <span data-bind="text: title"></span>
            <br>
        </a>
    </div>



</div>

<div class="practice-custom-section" data-bind="scope: 'custom_section_compare_data'">

    <h3 data-bind="text: compareproducts().countCaption"></h3>

</div>

<!-- <div class="practice-custom-section" data-bind="scope: 'custom_section_compare_data'">

    <h3 data-bind="text: custominfo().data"></h3>

</div> -->

<script type="text/x-magento-init">
    {
    	"*": {
        	"Magento_Ui/js/core/app": {
            	"components": {
                	"custom_section_data": {
                    	"component": "Practice_Blog/js/section"
                	},
                    "custom_section_compare_data": {
                    	"component": "Practice_Blog/js/custom_section"
                	}
            	}
        	}
        }
	}
</script>
