<a href="http://magento2.test:81/blog/all">All Blog</a>
<?php

($block->getIdentities());
$blogComments = $block->getBlogComments();
$blogCollection = $block->getBlogContent();
$blogCategories = $block->getBlogCategory();
// var_dump($blogComments->getData());
// die();
$blogId = 0;
$saveCommentUrl = $block->getUrl('*/comment/save');
$loginUrl = $block->getUrl('customer/account/login/referer/aHR0cDovL21hZ2VudG8yLnRlc3Q6ODEvYmxvZy9zaG93L2luZGV4L2lkLzEv/');

$isLogged = $block->checkIsLogin();


?>
<?php foreach ($blogCollection as $blogContent) : ?>
    <div class="container">
        <header class="blog-post-header">
            <h2 class="title mb-2"><?= $blogContent->getTitle() ?></h2>
            <div class="meta mb-3">
                <strong>Author: <?= $blogContent->getFirstname() . ' ' . $blogContent->getLastname() ?></strong>

                <span class="date"><?= date("d/m/Y H:i", strtotime($blogContent->getCreatedAt()));  ?></span>
            </div>
        </header>

        <div class="blog-post-body">
            <p><?= $blogContent->getContent() ?></p>
        </div>
    </div>
<?php endforeach; ?>


<?php foreach ($blogCategories as $category) : ?>
    <span><button><?= $category->getBlogCategoryName() ?></button></span>
<?php endforeach; ?>

<style>
    input[type=text], select {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
}

button[type=submit] {
  width: 20%;
  background-color: #4CAF50;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

button[type=submit]:hover {
  background-color: #45a049;
}

</style>
