<a href="http://magento2.test:81/blog/all">All Blog</a>
<h2>Show</h2>
<?php
$blogComments = $block->getBlogComments();
$blogContentCollection = $block->getBlogContent();
$blogAttributes = $block->getBlogAttributes();
// var_dump($blogComments);
// die();

foreach($blogComments as $comment){
    echo($comment->getContent());

}

?>

<?php foreach ($blogContentCollection as $blogContent) : ?>
    <h3><?= $blogContent->getTitle() ?></h3>
    <strong>Author:  <?= $blogContent->getFirstname().' '. $blogContent->getLastname() ?></strong>
    <p><?=date("H:i d/m/Y", strtotime($blogContent->getCreatedAt()));  ?></p>


    <?= $blogContent->getContent() ?>
<?php endforeach; ?>
