<a href="http://magento2.test:81/blog/all">All Blog</a>
<?php

($block->getIdentities());
$blogComments = $block->getBlogComments();
$blogCollection = $block->getBlogContent();
$blogCategories = $block->getBlogCategory();
// var_dump($blogComments->getData());
// die();
$blogId = 0;
$saveCommentUrl = $block->getUrl('*/comment/save');
$loginUrl = $block->getUrl('customer/account/login/referer/aHR0cDovL21hZ2VudG8yLnRlc3Q6ODEvYmxvZy9zaG93L2luZGV4L2lkLzEv/');

$countComment = $block->getCountApprovedComments();
$isLogged = $block->checkIsLogin();


?>
<?php foreach ($blogCollection as $blogContent) : ?>
    <div class="container">
        <header class="blog-post-header">
            <h2 class="title mb-2"><?= $blogContent->getTitle() ?></h2>
            <div class="meta mb-3">
                <strong>Author: <?= $blogContent->getFirstname() . ' ' . $blogContent->getLastname() ?></strong>

                <span class="date"><?= date("d/m/Y H:i", strtotime($blogContent->getCreatedAt()));  ?></span>
                <strong><?=$countComment ?></strong>
            </div>
        </header>

        <div class="blog-post-body">
            <p><?= $blogContent->getContent() ?></p>
        </div>
    </div>
<?php endforeach; ?>


<?php foreach ($blogCategories as $category) : ?>
    <span><button><?= $category->getBlogCategoryName() ?></button></span>
<?php endforeach; ?>

